steps:
  # 1. Build & Push Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ingestion-agent:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/ingestion-agent:latest'
      - '--build-arg'
      - 'CACHE_BUST=$(date +%s)'
      - '-f'
      - 'agents/ingestion-agent/Dockerfile'
      - '.'

  

  # 2. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ingestion-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ingestion-agent:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_REGION=${_REGION},LOCATION=${_REGION},PYTHONUNBUFFERED=1,DEPLOY_TIMESTAMP=$(date +%s)'


substitutions:
  _REGION: europe-west1

images:
  - 'gcr.io/$PROJECT_ID/ingestion-agent:latest'

options:
  logging: CLOUD_LOGGING_ONLY
